version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432
    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local
