name: Update README with Ruby and Rails versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Run Ruby script to update README
        run: ruby update_readme_versions.rb

      - name: Set git config
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Commit and push changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with Ruby and Rails versions"
          git push
